#!/bin/bash

aws_access_key_id=$(aws configure get aws_access_key_id)
aws_secret_access_key=$(aws configure get aws_secret_access_key)
aws_session_token=$(aws configure get aws_session_token)
aws_region=$(aws configure get region)

if [[ $1 = "run" ]]; then
    docker $1\
     -e AWS_ACCESS_KEY_ID=$aws_access_key_id \
     -e AWS_SECRET_ACCESS_KEY=$aws_secret_access_key \
     -e AWS_SESSION_TOKEN=$aws_session_token \
     -e AWS_REGION=$aws_region \
     ${@:2}
else
    docker $@
fi